"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICONBAR_HEIGHT = exports.LINE_HEIGHT_RATIO = exports.SINGLEBYTE_CHAR_WIDTH = exports.MULTIBYTE_CHAR_WIDTH = exports.SINGLEBYTE_CHAR_COEFFICIENT = exports.MULTIBYTE_CHAR_COEFFICIENT = exports.DEFAULT_FONT_SIZE = exports.DEFAULT_SECTION_HEIGHT = exports.MIN_WIDTH = exports.MAX_WIDTH = exports.Y_OFFSET = exports.X_OFFSET = exports.CURVE_CONTROL_OFFSET = exports.ARROW_OFFSET = exports.NODE_HEIGHT = exports.PRESET_Y = exports.DEFAULT_Y = exports.DEFAULT_X = exports.DEFAULT_ZOOM_RATIO = void 0;
// src/constants/Node.js
exports.DEFAULT_ZOOM_RATIO = 1;
exports.DEFAULT_X = 50;
exports.DEFAULT_Y = 50;
exports.PRESET_Y = 50;
exports.NODE_HEIGHT = 60;
exports.ARROW_OFFSET = 20;
exports.CURVE_CONTROL_OFFSET = 80;
exports.X_OFFSET = 100;
exports.Y_OFFSET = 10;
exports.MAX_WIDTH = 200;
exports.MIN_WIDTH = 80;
exports.DEFAULT_SECTION_HEIGHT = 20;
exports.DEFAULT_FONT_SIZE = 12;
exports.MULTIBYTE_CHAR_COEFFICIENT = 1;
exports.SINGLEBYTE_CHAR_COEFFICIENT = 0.5;
exports.MULTIBYTE_CHAR_WIDTH = 14;
exports.SINGLEBYTE_CHAR_WIDTH = 7;
exports.LINE_HEIGHT_RATIO = 1.4;
exports.ICONBAR_HEIGHT = 40;
